name: launch_at_startup
description: This plugin allows Flutter desktop apps to Auto launch on startup / login.
version: 0.2.3
publish_to: none
homepage: https://github.com/leanflutter/launch_at_startup

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.5
  win32_registry:
    git:
      url: https://github.com/kamilkarp/win32_registry.git
      ref: e313b04a58ad00bf680e44d3e8084973124005b8

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
