name: launch_at_startup
description: This plugin allows Flutter desktop apps to Auto launch on startup / login.
version: 0.2.3
publish_to: none
homepage: https://github.com/leanflutter/launch_at_startup

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.5
  win32_registry: ^1.0.2
  win32_registry_observer:
    git:
      url: https://github.com/kamilkarp/win32_registry_observer.git
      ref: 6de1516edcc9a0e4607701ad06e77474a148ce9b

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
